name: Deploy Application Docker Image to EC2 instance

on:
  push:
    branches: [main]

jobs:

  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted

    steps:
      - name: Checkout latest code (force clean)
        uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest image from ECR
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest

      - name: Stop and remove container on port 5000
        run: |
          ID=$(docker ps -q --filter "publish=5000")
          if [ -n "$ID" ]; then
            docker stop $ID
            docker rm $ID
          fi

      - name: Remove old container by name
        run: |
          if [ "$(docker ps -aq -f name=vehicle_app)" ]; then
            docker stop vehicle_app || true
            docker rm vehicle_app || true
          fi

      - name: Remove old image
        run: |
          docker rmi ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest || true

      - name: Run latest Docker image
        run: |
          docker run -d \
            -p 5000:5000 \
            --name vehicle_app \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
